# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XAO-FS
version:      1.06
version_from: FS.pm
installdirs:  site
requires:
    DBD::mysql:                    2.0414
    DBI:                           1.13
    Error:                         0.15
    Pod::Usage:                    1.12
    Test::Unit:                    0.15
    XAO::Base:                     1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
